light_source: 'LED'
calib_type: 'Flatfield'
LEDS: {'u': ['M385L3'], 'g': ['M455L4','M505L4'],'r':['M565L3','M660L4'],'i':['M730L5','M780LP1'],'z':['M850LP1','M940L3',],'y4':['M970L4']}
dichroic_files: {'u':'DMLP735B_RawData.csv','i':'curv_69904.csv','g':'DMLP490.csv','r':'DMLP605.csv','z':'DMLP900.csv','y4':'DMLP735B_RawData.csv'}
coating_type: {'u':'A','g':'A','r':'A','i':'B','z':'B','y4':'B'}
snr: 1000
use_fiber: False 
f_lsst: 10.3  
pixel_size: .000010 
m1: 'Protected-Ag'
m2: 'Protected-Ag'
m3: 'Protected-Ag'
detector_file: 'detector_e2vPrototype.dat'
corrector_lenses: ['lens1.dat','lens2.dat','lens3.dat']
total_number_of_pixels: 3200000000
cam_readout: 2  #Double check this
min_exptime: 13
electrometer_readout: 0 #How to deal with this? This will matter for CBP measurements for sure
spectrograph_readout: 0
projector_design: ['collimator','mirror_al_f01','converging_bk7','converging_bk7','converging_bk7']
system_efficiency: 0.00010959 #0.496  #from zemax
reflector_reflectance_file: 'scaled_reflector_reflectance.csv' #0.804mirr 